#import "lib.typ": *

#fig("fig09.png", [Induction of a classifier in supervised learning. Source: [123].], width: 75%)

Fig. 9 illustrates graphically what has been explained, but in this case the set $D$, or the
#emph[corpus], is represented by $x_1, x_2, ..., x_n$ --- these being the documents --- forming
a matrix that may carry the classes, or labels, represented by $y_1, y_2, ..., y_n$, which supply
information to the classifier $f(x)$.

== 3.5. Classification algorithms

This chapter presents the classifier used in this dissertation and the probabilistic model
employed to identify groups of topics, which will help obtain unclassified content while
avoiding any kind of strong assumption about the relationship between the text and the
categories, using only the distribution of words over topics.

=== 3.5.1. SVM

SVM is a versatile classifier model, capable of linear and non-linear classification, of regression,
and even of outlier detection. This model was developed by the Russian Vladimir Vapnik, and
has at its foundation statistical learning theory, which is grounded in the errors of the learning
technique against the validation data, or generalization error, bounded by the training error [83,
123].

The SVM technique is used in this dissertation to carry out text categorization tasks,
automatically assigning one or more predefined categories to text documents. SVM can also be
used in character recognition, such as signature recognition systems, in bioinformatics, assisting
in the understanding of genetic structures, and in email classification, helping decide between a
good email and spam, among other uses [124, 125].

The workings of SVM use the concept of supervised classification. The aim is to make
the machine capable of classifying objects --- or, in the case of this dissertation, texts labeled
into distinct classes --- from earlier examples, so that it is able to classify new inputs (new texts)
into the class they will belong to. The SVM technique can be applied in two ways: use on
information that is in linear form, which can be separated by a hyperplane (linear SVM), and
the non-linear SVM form, where the information is in a pattern that cannot be separated by a
hyperplane. This non-linear type of SVM maps the training set, which lies within its original
space, into a space of higher dimensions known as the feature space [138, 140]. Fig. 10 (a)
presents a training set that does not have non-linear data, and Fig. 10 (b) shows the training set
in a space of higher dimensions. For this dissertation the linear SVM classifier will be used [38,
123].

#fig("fig10.png", [Example of non-linear SVM with the feature space. Source: [139, 140].])

The idea behind the SVM classifier is simple to interpret: in the training process, which
contains the labeled data, the SVM classifier examines the input data and identifies patterns in
two half-spaces corresponding to the two classes, with the hyperplane separating these spaces.
All input data are represented as points in that space and are mapped to the output categories in
such a way that the categories are divided by the largest and clearest possible gap. Fig. 11 shows
what has been exemplified above [42, 48, 83, 123, 127].

#fig("fig11.png", [Representation of the hyperplane generated by the SVM classifier and its margins.], width: 80%)

The hyperplane is determined as a mapping function $y = f(x)$ between a
multidimensional feature vector $x$ and a quantity, or a set of them, in $y$. To produce the
mapping, the only information available is the training set, conceived as
$D = (x_i, y_i) in X times Y$, $i = 1, ..., l$, with $l$ being the number of pairs $(x_i, y_i)$ in the
sample [38, 140].

The equation of the hyperplane in $RR^d$ is:

$ f(x) = w x + b = 0 $

#noind[where, in equation (3):]

#set par(first-line-indent: 0pt)
#block(inset: (left: 1.25cm))[
  $w$: is the vector representing the set of inputs, known as the weight vector;

  $x$: are the points on the hyperplane;

  $b$: is the distance between the hyperplane and the point of origin.
]
#set par(first-line-indent: (amount: 1.25cm, all: true))

From equation (3) the hyperplane can separate the data into two regions, namely
$f(x) > 0$ and $f(x) < 0$ [131, 132, 140], and the sign function can be used, as can be seen in
equation (4).

$ h(x) = op("sgn")(f(x)) = cases(
  -1 &"if" w dot x + b < 0,
  +1 &"if" w dot x + b > 0,
) $

Here $+1$ and $-1$ represent the respective classes. Given the possibility of obtaining
several hyperplanes, it can be deduced that the best hyperplane for separating the classes is the
one with the largest margin between the classes, which is called the optimal hyperplane. The
margin is defined as twice the distance from the hyperplane (the line) to the nearest data point.
In this case it can be deduced that if a margin with a large distance between the classes is
obtained, then the error associated with classifying new input data will be smaller [132].

For the best hyperplane it is necessary to define the support vectors, which are the data
points of both classes that lie close to the class separator (the optimal hyperplane; see Fig. 11)
[133].

Fig. 11 shows the support vectors with their margins; this vector can be represented by
equation (5):

$ abs(w dot x_i + b) = 1; quad i = 1, 2, ..., n. $

#noind[where, in equation (5):]

#set par(first-line-indent: 0pt)
#block(inset: (left: 1.25cm))[
  $i$: position of the object;

  $n$: number of objects in the set;

  $x_i$: corresponds to a particular data point.
]
#set par(first-line-indent: (amount: 1.25cm, all: true))

#noind[This equation (5) satisfies the following constraints:]

$ cases(
  w dot x_i + b >= +1 &"if" y_i = +1,
  w dot x_i + b <= -1 &"if" y_i = -1,
) quad i = 1, 2, ..., n. $

#noind[where:]

$y_i$: $y_i in {-1, +1}$. These values represent the classification value of $x_i$, defining
whether the data point lies in the part greater than zero or in the part less than zero of the
classifier. Equation (6) can be summarized in equation (7):

$ y_i (w dot x_i + b) - 1 >= 0; quad i = 1, 2, ..., n. $

#noind[Referring to the constraints $y_i (w dot x_i + b) - 1 >= 0$:]

$ y_i (w dot x_i + b) - 1 >= 0, quad forall i = 1, ..., n. $

The optimal hyperplane is found by maximizing the margin. This maximization of the
margin is obtained by minimizing, or reducing, $norm(w)$; see equation (9) [131]:

$ op("Minimize")_(w, b) 1/2 norm(w)^2 $

#noind[where:]

#block(inset: (left: 1.25cm))[
  $norm(w)$: is the Euclidean norm of $w$, $norm(w) = sqrt(w * w)$.
]

In this way it can be guaranteed that no data point will lie between the margins; this is
the characterization of linear SVM with hard margins. In order to solve the problem of
minimizing $norm(w)$ subject to the constraints of equation (9), the method of Lagrange
multipliers [134] is used, which supplies the maximum and minimum of a function subject to a
constraint.

$ L(w, b, lambda) = 1/2 norm(w)^2 - sum_i lambda_i (y_i (w dot x_i + b)) - 1 $

#noind[where:]

#block(inset: (left: 1.25cm))[
  $lambda_i$: are the Lagrange multipliers.
]

For an optimal solution, it is necessary to minimize the Lagrange function by maximizing
the Lagrange multipliers $(lambda)$ and minimizing $w$ and $b$ [135]; the following
optimization problem was obtained:

$ op("Maximize")_(lambda_i) sum_(i=1)^n lambda_i - 1/2 (w times x_i + b) $

$ "With the constraints:" cases(
  lambda_i >= 0\, &forall i = 1, ..., n,
  b = 0,
) $

$ w = sum_(i=1)^n lambda_i x_i y_i quad "and" quad b = sum_(i=1)^n lambda_i y_i $

The optimization problem seen in equation (13) has a single global maximum [137] that
can be found, and may be expressed in equation (14):

$ h(x) = op("sgn") ( sum lambda_i y_i (x_i x) + b ) $

With the function $lambda_i$ different from zero, these are the data points called support
vectors, being the points closest to the hyperplane; for the remaining data points
$lambda_i = 0$ [136]. The classifying function is therefore:

$ f(x) = sum lambda_i y_i x_i x + b $

This confirms that the hyperplane obtained by the equations explained above is able to
classify the data that fall within the parameter of equation (3), demonstrating that these data are
linearly separable [137, 140].
