#import "lib.typ": *

#noind[
  To carry out this procedure on the content of the #emph[corpus], preprocessing of the articles
  is required, as follows:
]

#set par(first-line-indent: 0pt)
#list(
  spacing: 0.6em,
  [Removal of punctuation and other kinds of unnecessary characters with the help of
   tokenization and regex-based NLP techniques.],
  [Removal of stopwords.],
  [Lemmatization: in this work this technique was used because it shows fewer losses in the
   sentences, or in the sense of the phrases, when terms are joined using the unigram and bigram
   technique.],
)
#set par(first-line-indent: (amount: 1.25cm, all: true))

After this procedure, the #emph[corpus] produced by the screening is better suited to
passing through the classification process proposed for supporting the SR.

Since the probabilistic method used in this dissertation is provided by the Gensim library,
it creates two types of data used by the LDA statistical model, namely: the dictionary and the
#emph[corpus], which in this case is represented as a BoW model. The dictionary holds a record
of all the words contained in the #emph[corpus], assigning an identifier to each term, as can be
seen in Fig. 22.

The BoW generated by LDA is a fitting of all the documents, having in its composition
the matrix representation between articles and words. With the words represented by numeric
identifiers and the frequency count occurring in the document, its use is for the purpose of
searching for patterns in the term--document matrix; this can be seen in Fig. 23 [18, 64].

#fig("fig22.png", [A small example of the dictionary used by the LDA model.])

#fig("fig23.png", [A small example of the BoW used by the LDA model, containing only the
references as word ids and the number of times they appear in the article.])

At the stage of preparing the dictionary and the BoW, LDA applies a filter to manage the
number of terms that lie within a bound, which must not be too present or too little present in
the articles, since they can distort the results; the bound is therefore set between 0.2% and 80%.
In this way, the topics will be formed only by words with occurrences in this interval [39, 108].

With the #emph[corpus] and the dictionary processed by LDA, the number of topics can
be defined, where $k$ is the representation of that number, denoted among the values
$k = 10, 20, 50, 100, 150$ and $200$. In reality, however, there is no value of $k$ that serves all
topic-based events. This number is generally based on prior knowledge of the information base
one has. In the case of a small collection of texts, this number of topics will obviously not be
very large.

The value of $k$ helps improve the representation of the terms in topics, its access being
to the base of articles present in the #emph[corpus]. For this, the value uses two
hyperparameters, $alpha$ and $beta$, which help define whether the topics will be more general
or more detailed [39].

$ alpha = 1 / "number"_"topics" $

To obtain this information from the topic model, it is necessary to pass as parameters the
#emph[corpus], the dictionary, and the desired number of topics to the function representing
LDA. These are processed through the iteration of each value of $k$, with the results stored in
a variable created by the model, named by default #emph[model], or LDA model, containing
its model for the #emph[corpus] under analysis. This class is accessed through the Gensim
library for later evaluation of the extracted topics. Fig. 24 shows a short excerpt of the algorithm
representing the LDA model.

#fig("fig24.png", [Pseudocode of the LDA model. Note: the num_topics parameter is the same
as the term k.])

An interesting fact to note in the LDA model function in Python is the #emph[passes]
parameter (Fig. 25). This controls the frequencies, or cycles, with which the model's topics are
grouped across the whole #emph[corpus], carrying out a review of each stage of the cycle that
the LDA class performs. This matter may be somewhat technical, but it is essential for
controlling the quality of the model that will be delivered. It is important to set the number of
passes so that the topic iterations are sufficient; the higher the number of passes, the longer the
execution of the LDA class will take, on account of the reviewing.

According to [108, 109], in order to choose the most exact number of pass iterations it is
advisable to enable the parameter that controls log perplexity (equation 24), setting it to a value
of 1. Processing the model with this parameter set to 1 will produce log lines similar to the
following:

#block(inset: (left: 1.25cm), text(size: 10.5pt)[
  2019-11-30 02:55:08,650 - gensim.models.MODELO_LDA - DEBUG - 50/530 documents
  converged within 100 iterations
])

If #emph[passes] = 25 is set, this line above will be observed 25 times for an exact
number. If the number of times the line above appears is not equal to 25, then it may be
concluded that the number in the #emph[passes] variable is not ideal, and may be either more
or less than 25 [109]. It is necessary to make sure that by the final cycles most of the documents
have converged. If everything happens as described, the number returned by log perplexity will
be the ideal one for taking part in the iterations of the LDA model. Another important factor to
develop for a good topic model is the question of parallelism; this work was developed with
processes of this technology.

The Gensim library makes available a technique by which the user can make use of the
cores of the computer's processor, thereby giving greater speed to the process of building the
LDA model. This step is marked by the parameter workers = cpu_count $-$ 1, where
cpu_count is a variable that will hold the number of CPUs. The $-1$ is a way of preventing the
user of the library from falling into the temptation of using all the processor cores [109]. Fig.
25 below shows the configuration of the LDA model used by the classification algorithm.

#fig("fig25.png", [LDA in Python: the parameters that make up the LDA function.])

In this work an LDA model was proposed with the value $k = 100$ and a number of
#emph[passes] = 25. The same configuration will later be used for the Mallet library. According
to the authors of [110, 111], Mallet is a Java-based package for statistical natural language
processing, document classification, clustering, topic modeling, information extraction, and
other machine learning applications on text.

Mallet uses Latent Dirichlet Allocation (LDA); Pachinko Allocation (PAM), a model that
captures arbitrary, nested, and possibly sparse correlations between topics using a directed
acyclic graph, providing a flexible alternative to the recent work of Blei and Lafferty (2006),
which captures correlations only between pairs of topics [112]; and Hierarchical Latent Dirichlet
Allocation (hLDA) for topic modeling, in which topics are gathered into a hierarchy using the
processes whose structure is learned from the data [113].

This library offers better topic quality than the pure LDA technique. Gensim makes
available a wrapper for implementing LDA together with Mallet. The LDA model used in
conjunction with the Mallet package is built with 100 different topics, where each topic is a
combination of key terms and each key term contributes a certain weighting to the topic, as seen
in section 3.5.2.

#fig("fig26.png", [Topics in the LDA model and the model being used with the Mallet library.])

Fig. 26 may be interpreted as follows. Topic 72 of the classification carried out with the
Mallet library will be analyzed. It can be described by the 10 main keywords that contribute to
this topic, which are 'cancer', 'treatment', and so on, and the weight of 'cancer' in topic 72 is
0.069. The weights reflect the importance of a keyword to the chosen topic, offering a simple
way of examining the theme that the topic is dealing with. In this case, for topic 72, it can be
observed that the theme is cancer treatment and its consequences.

#fig("fig27.png", [Another way of viewing the main topics using the Python package pyLDAvis.])

For a better visualization than that of Fig. 26, the pyLDAvis package, found in the
Gensim library, is used. It offers a dynamic way of analyzing the terms that may be shared by
different topics.

Fig. 27 shows that the bubbles in the chart on the left-hand side represent the topics,
where their importance is measured by their size. When the topic model has large bubbles that
do not overlap one another and are spread across the chart, it may be considered a good model.
When $k$ is very large, there will be overlapping of topics in small bubbles at a particular
position in the chart, causing granularity in the subtopics that make up the topics [114].

So that no time is lost in manually searching for a suitable number of topics, it is often
necessary to use calculations by means of coherence. This measure is taken through the ideal
number of $k$ topics, with $n = 1, 2, 3, ..., k$ being analyzed for this question, and choosing
the one that offers the highest coherence value (see section 3.5.2).
