#import "lib.typ": *

#fig("fig36.png", [Example of the implementation of the k-folds cross-validation technique.], width: 70%)

With the value $K = 4$, the #emph[corpus] was divided into 354 articles for training and
176 articles for testing, which are then processed for feature extraction with the TF-IDF
statistical measure. Fig. 37 below presents a piece of the code for the part that extracts the
features from the text files:

#fig("fig37.png", [Demonstration of feature extraction from the articles with the TF-IDF statistical measure.], width: 75%)

This resource creates the TF-IDF matrix, which computes the word count values, creates
a model based on the TF-IDF measures, and helps convert text data into numeric format, where
the vector value it generates is the product of those two terms. TfidfVectorizer provides a vector
named #emph[vectorizer]; so that it can be the feature model, the fit_transform function is
called, a transformer for fitting the data instances. This function is called by the
#emph[vectorizer] vector, which takes as a parameter the set of articles for training and testing
already divided by the k-folds method, these being iterable lists of strings in which each string
represents the contents of the documents contained in the #emph[corpus], the content of these
strings having a number of documents for each list. A short excerpt of the algorithm that forms
the classifier is shown in Fig. 38 [38, 119, 76].

#fig("fig38.png", [The function is called by the #emph[vectorizer] vector, which is the model
coming from the TfidfVectorizer function; this function takes X_train and X_test as parameters.], width: 75%)

The results generated by this fit_transform function are sparse matrices containing the
string of numbers of each document of the iterable list, being the word count weighted by the
TF-IDF statistical measure and the weights of the words per document of fixed length, for each
document in the training and test sets. This may also be called the term--document matrix [76].

After the texts contained in the #emph[corpus] have been processed into numeric format,
the SVM classifier can be trained, with its hyperparameter already adjusted by the grid search
technique. This classifier uses two parameters of the term--document matrix, these being
training and test together with the polarity classification labels originating from the
#emph[corpus]. The content of these labels, as mentioned, forms part of the manual
classification carried out by the human reviewers, which binds each article set aside for training
and for testing. Fig. 39 shows how the labels are used in the form of vectors.

#fig("fig39.png", [Extraction of the polarity labels of the classification.], width: 75%)

The training of the SVM classifier is carried out together with the k-fold technique, and
so are the TF-IDF weightings, not just the classifier. This can be explained by the fact that the
cross-validation method had to be implemented inside a loop, where at each validation iteration
both the TF-IDF part and the SVM part are processed.

At each iteration, the loop that makes up the cross-validation creates clones of the
classifier, trains those clones on the training part, and makes predictions on the test part,
counting the number of correct predictions and delivering their proportion through the confusion
matrix. This way of developing cross-validation is effective for gaining greater control over the
data to be classified [38]. Fig. 40 shows an excerpt of the implementation of the k-folds
technique in structured Portuguese (Portugol).

#fig("fig40.png", [Algorithm of the k-folds technique, written in structured algorithmic notation
(Portugol). Demonstration of the interactions of cross-validation with the classifier and the
TF-IDF method.])

The k-folds cross-validation with $K = 4$ --- that is, with 4 parts --- made it possible to
test all the files of the #emph[corpus], bearing in mind that, with the imbalance of this set of
articles, the classification was practically polarized in equal proportion (see Fig. 21), leading to
a fairer classification when obtaining the judgments for machine learning geared to the SR.

For a more detailed understanding of the algorithm proposed for supporting the SR, Fig.
41 shows in greater detail the whole development of the algorithm through flowchart modeling.

#fig("fig41.png", [Flowchart diagram representing each stage of the classifier algorithm.], width: 88%)

== 4.4. Discussion of the results

With a total of 530 articles balanced and polarized as "relevant" and "not relevant," the number
of articles predicted correctly and the number of articles classified incorrectly by the classifier
are presented, and alongside them a comparison can be made between the balanced and the
unbalanced #emph[corpus] with their classifications.

#fig("fig42.png", [Confusion matrix with the balanced and unbalanced corpus and their metrics.])

As noted in subchapter 3.5.3, the confusion matrix exposes a great deal of information
that needs to be analyzed in more detail. Fig. 42 shows, on the left-hand side, the confusion
matrix with the classified and balanced #emph[corpus], and on the right-hand side the confusion
matrix with the classification of the unbalanced #emph[corpus]. Each row of the matrix
represents an actual class, while each column represents a predicted class.

The first row of the balanced confusion matrix considers the "not relevant" articles: 216
of them were correctly classified as "not relevant," which is called a true negative, TN. In the
second quadrant, on the same row as the first quadrant, 49 articles were wrongly classified as
"relevant," which is a false positive, FP. In the second row, that is in the third quadrant, the
"relevant" articles are considered: 33 articles were wrongly classified as "not relevant," called a
false negative, FN, while 232 articles were classified as "relevant," which is called a true
positive, TP.

One observation to be noted for a perfect classifier is that it would have only true
positives TP and true negatives TN, so that the confusion matrix would have non-zero values
only on its main diagonal (upper left to lower right). As can be seen, with this #emph[corpus]
used with the hyperparameter adjustment and balanced, an almost perfect classification was
obtained [38].

As observed in the matrix with the imbalanced #emph[corpus] in Fig. 42, at a ratio of
4.27 "not relevant" articles to 1 "relevant" article, it can be seen that the concentration of articles
as FN, false negative, in the imbalanced #emph[corpus] is very large, with 94 articles wrongly
classified as "not relevant."

Following the same steps as the example of the results for the balanced #emph[corpus],
it is notable that balancing the information contained in the dataset is important for obtaining
answers with greater precision, helping both with classification and with the organization of the
information.

It may be deduced that information, when it has a more balanced classification, yields as
a result greater precision and confidence when using the classifier on the data provided. This
can be seen in Table 4, which compares the metrics between the two types of #emph[corpus].

Tables 4 and 5 below present, with better visualization, the comparison of the metrics of
the SVM classifier with the balanced and the unbalanced dataset.

#let bar(v, color) = box(
  width: 4.6cm * (v / 120), height: 0.52em, fill: color,
)
#let barrow(label, nb, b) = (
  [#label],
  [#bar(nb, rgb("#4e79c4")) #text(size: 9pt)[#nb]],
  [#bar(b, rgb("#e8893c")) #text(size: 9pt)[#b]],
)

#tbl(
  block(width: 100%)[
    #set par(first-line-indent: 0pt)
    #align(center, text(size: 11pt, style: "italic")[
      Comparison of SVM classification with both types of corpus
    ])
    #v(0.6em)
    #table(
      columns: (2.6cm, 1fr, 1fr),
      stroke: none,
      align: (left + horizon, left + horizon, left + horizon),
      inset: 5pt,
      [], [#text(size: 9.5pt)[#box(width: 0.8em, height: 0.8em, fill: rgb("#4e79c4")) Not balanced]],
          [#text(size: 9.5pt)[#box(width: 0.8em, height: 0.8em, fill: rgb("#e8893c")) Balanced]],
      ..barrow([Precision], 48.9, 96.6),
      ..barrow([Recall], 40, 63),
      ..barrow([Accuracy], 49, 81),
      ..barrow([F1 score], 45, 56),
    )
  ],
  [Comparison of the classification between both states of the corpus.],
)

#tbl(
  table(
    columns: 3,
    stroke: 0.5pt,
    inset: 7pt,
    align: (left, center, center),
    table.header(
      [],
      [#text(weight: "bold")[Not balanced]],
      [#text(weight: "bold")[Balanced]],
    ),
    [Precision], [48.9], [96.6],
    [Recall], [40], [63],
    [Accuracy], [49], [81],
    [F1 score], [45], [56],
  ),
  [Comparison of the classification between both states of the corpus, with their percentages.],
)

As can be seen, there is a great difference between the two types of result for the two
states of the #emph[corpus]. The more balanced it is, the better the results will be, and the
quantity of information will be taken into account, yielding a better proportion in the results.

To make the reviewers' work easier by sparing them from reading the whole abstract,
which can be long, text summarization is used at this point in the classification of the articles.
This helps the researcher gain a better advance sense of the content of the abstract, making it
easier to know whether, even with the classification complete, that same article really would be
what the researcher wants --- bearing in mind that the supervised classifier proposed in this
dissertation does not replace the human work of making a more complete and precise
classification.

Fig. 43 shows the result of the summarization of the abstract of article Doc no. 16474;
this field is the original index that the reviewers gave to each article out of a total of 530
contained in the balanced #emph[corpus]. This summarization is based on the content analyzed
statistically by the LDA model with Mallet, and can be carried out with the help of the Gensim
library using the TextRank function.

#fig("fig43.png", [Summarization of the articles, covering the abstract of each document.])

Fig. 44 presents what the content of the abstract of the same article was in the list before
summarization.

#fig("fig44.png", [Content of the article with index 16474 before summarization.])

Together with the summarization, the recognition of the NEs contained in the abstract is
also presented, as mentioned and explained in section 3.7. See Fig. 45.

#fig("fig45.png", [Entity recognition in the summarization of the abstracts.])
