#import "lib.typ": *

= Bibliography

#set par(first-line-indent: 0pt, justify: true)
#set text(size: 11pt)

#let refs = (
  (1, "Newton, I. - 1676. \"Letter from Sir Isaac Newton to Robert Hooke\". Historical Society of Pennsylvania. Retrieved 22 March 2020."),
  (2, "Brocke, V. - Et Al., 2009. Reconstructing the giant: on the importance of rigour in documenting the literature search process. Paper presented at the Proceedings of the 17th European Conference on Information Systems (ECIS 2009); Verona, Italy. 2009."),
  (3, "Paré G., Trudel M.- C., Jaana M., Kitsiou S. Synthesizing information systems knowledge: A typology of literature reviews. Information & Management. 2015;52(2):183–199."),
  (4, "Lau F., Kuziemsky C., editors. Handbook of eHealth Evaluation: An Evidence-based Approach. Victoria (BC): University of Victoria; 2016."),
  (5, "Levy Y., Ellis T.J. A systems approach to conduct an effective literature review in support of information systems research. Informing Science. 2006;9:181–211."),
  (6, "Green B. N., Johnson C. D., Adams A. Writing narrative literature reviews for peerreviewed journals: secrets of the trade. Journal of Chiropractic Medicine. 2006;5(3):101– 117. [PMC free article] [PubMed]"),
  (7, "J. S. Brainard, N. Jones, I. Lake, L. Hooper, P. Hunter. 2020. Facemasks and similar barriers to prevent respiratory illness such as COVID-19: A rapid systematic review. medRxiv doi: https://doi.org/10.1101/2020.04.01.20049528"),
  (8, "E. Mullins, D. Evans, R.M. Viner, P. O’Brien, E. Morris. 2020. Coronavirus in pregnancy and delivety: rapid review and expert consensus. medRxiv doi: https://doi.org/10.1101/2020.03.06.20032144"),
  (9, "Gagnon MP. Hospital-based health technology assessment: developments to date. Pharmacoeconomics. 2014;32(9):819–24. doi:10.1007/s40273-014-0185-3."),
  (10, "L. Bornmann, R. Mutz. Growth rates of modern science: A bibliometric analysis based on the number of publications and cited references. J. Assoc. Inf. Sci. Technol., 2014."),
  (11, "Landhuis, E. Scientific literature: Information overload. Nature 535, 457–458 (2016). https://doi.org/10.1038/nj7612-457a"),
  (12, "Tsertsvadze, A., Chen, Y., Moher, D. et al. How to conduct systematic reviews more expeditiously?. Syst Rev 4, 160 (2015). https://doi.org/10.1186/s13643-015-0147-7"),
  (13, "R.M. Featherstone, D.M. Dryden, M. Foisy, J.M. Guise, M.D. Mitchell, R.A. Paynter, et al. Advancing knowledge of rapid reviews: an analysis of results, conclusions and recommendations from published review articles examining rapid reviews. Syst Rev. 2015;4:50. doi:10.1186/s13643-015-0040-4."),
  (14, "E. Mullins, D. Evans, R.M. Viner, P. O’Brien, E. Morris. 2020. Coronavirus in pregnancy and delivety: rapid review and expert consensus. medRxiv doi: https://doi.org/10.1101/2020.03.06.20032144"),
  (15, "Jonnalagadda S.R., Goyal P., Huffman M.D.. Automating data extraction in systematic reviews: a systematic review. Syst Rev. 2015;4:78."),
  (16, "O’Mara-Eves A, Thomas J., McNaught J., Miwa M., Ananiadou S. Using text mining for study identification in systematic reviews: a systematic review of current approaches. Syst Rev. 2015;4:5."),
  (17, "I. J. Marshall, B. C. Wallace. Toward systematic review automation: a practical guide to using machine learning tools in research synthesis. Systematic Reviews (2019)8:163."),
  (18, "Kitchenham B.A., Brereton P., Budgen D., Turner M., Bailey J., Linkman S. Systematic literature reviews in software engineering – A systematic literature review. Inf. Softw. Technol.. 2009;51(1):7–15."),
  (19, "Silva, F.Q. da, Santos, A.L., Soares, S., Franca, A.C.C., Monteiro, C.V., Maciel, F.F. (2011) Six years of systematic literature reviews in software engineering: an updated tertiary study. Inf. Softw. Technol., v. 53, n. 9, p. 899-913."),
  (20, "M. Makoto, J.Thomas, A. O’Mara-Eves, S. Ananiadou. 2013. Reducing systematic review workload through certainty-based screening. (2014), DOI: https://doi.org/10.1016/j.jbi.2014.06.005"),
  (21, "Felizardo, K.R; Nakagawa, E.Y; Ferraz Febbri, S.C.P; Ferrari, F. C – Revisão Sistemática da literatura em engenharia de software, Teoria e Prática, 1ª ed. Editora Elsevier, 2017. ISBN (versão digital): 978-85-352-8597-0"),
  (22, "Sackett D.L., Rosenberg W.M.C., Gray JAM, Haynes R.B., Richardson W.S.. Evidence based medicine: what it is and what it isn’t. Br. Med. J..1996;1(316):71–72."),
  (23, "Kitchenham, B.A. (2004) Procedures for performing systematic reviews. Joint Technical Report. Software Engineering Group Department of Computer Science Keele University, Keele, UK and Empirical Software Engineering National ICT Australia, Eversleigh, Austrália."),
  (24, "Zhang H., Babar M.A.. Systematic reviews in software engineering: An empirical investigation. Inf. Softw. Technol.. 2013;55(7):1341–1354."),
  (25, "Marshall C. Systematic Review (SR) toolbox 2015. http://systematicreviewtools.com/. Accessed 05 November 2015."),
  (26, "Balk E.M., Chung M., Chen M.L., Trikalinos T.A., Kong Win Chang L. Assessing the accuracy of google translate to allow data extraction from trials published in non-english languages. Rockville (MD). 2013. http://effectivehealthcare.ahrq.gov/index.cfm/search-forguides-reviews-and-reports/?productid=1386&pageaction=displayproduct. Accessed on 5 November 2015."),
  (27, "Gartlehner, G., Wagner, G., Lux, L. et al. Assessing the accuracy of machine-assisted abstract screening with DistillerAI: a user study. Syst Rev 8, 277 (2019). https://doi.org/10.1186/s13643-019-1221-3"),
  (28, "Distiller S.R., Disponível em: <https://www.evidencepartners.com/products/distillersrsystematic-review-software/> [Acessado em 18/05/2020]"),
  (29, "Lanera, C., Berchialla, P., Sharma, A. et al. Screening PubMed abstracts: is class imbalance always a challenge to machine learning?. Syst Rev 8, 317 (2019). https://doi.org/10.1186/s13643-019-1245-8"),
  (30, "Bannach-Brown, A., Przybyła, P., Thomas, J. et al. Machine learning algorithms for systematic review: reducing workload in a preclinical review of animal studies and reducing human screening error. Syst Rev 8, 23 (2019). https://doi.org/10.1186/s13643-019-0942-7"),
  (31, "Rezende, S. - Sistemas Inteligentes: Fundamentos e Aplicações, 1ª ed. Editora Manole Brasil, 2003. ISBN: 85-204-1683-7"),
  (32, "Grus, J. - Data Science do Zero, Primeiras Regras com Python, 1ª ed. Editora Alta Books, 2016. ISBN 978-85-7608-998-8"),
  (33, "Tsuruoka Y, Miwa M, Hamamoto K, Tsujii J, Ananiadou S. Discovering and visualizing indirect associations between biomedical concepts. Bioinformatics 2011;27(13): i111–9."),
  (34, "Ananiadou S, McNaught J. Text mining for biology and biomedicine. Boston/London: Artech House; 2006."),
  (35, "Sasaki Y, Rea B, Ananiadou S. Clinical text classification under the open and closed topic assumptions. Int J Data Mining Bioinform 2009;3(3):299–313."),
  (36, "Wallace B, Trikalinos T, Lau J, Brodley C, Schmid C. Semi-automated screening of biomedical citations for systematic reviews. BMC Bioinform 2010;11(1):55."),
  (37, "Cortes C., Vapnik V. Support-vector networks. Mach Learn 1995;20(3):273–97."),
  (38, "Géron, A. - Mãos à Obra: Aprendizado de Máquina com Scikit-Learn & TensorFlow: Conceitos, Ferramentas e Técnicas para construção de Sistemas Inteligentes, 1ª ed. Editora Alta Books, 2019. ISBN: 978-85-508-0381-4."),
  (39, "Blei, D. M.; NG, A. Y.; Jordan, M. I. Latent dirichlet allocation. J. Mach. Learn. Res., JMLR.org, v. 3, p. 993–1022, mar. 2003. ISSN 1532-4435. Disponível em: <http://dl.acm.org/citation.cfm?id=944919.944937>"),
  (40, "Bannach-Brown, A., Przybyła, P., Thomas, J. et al. Machine learning algorithms for systematic review: reducing workload in a preclinical review of animal studies and reducing human screening error. Syst Rev 8, 23 (2019). https://doi.org/10.1186/s13643-019-0942-7"),
  (41, "Cohen A.M., Adams C.E., Davis JM, Yu C, Yu PS, Meng W, et al. Evidence-based medicine, the essential role of systematic reviews, and the need for automated text mining tools. In: Proceedings of the 1st ACM international Health Informatics Symposium: ACM; 2010. p. 376–80."),
  (42, "S. Haykin. Neural Networks - A Compreensive Foundation. 2ª Ed. New Jersey: PrenticeHall, 1999."),
  (43, "PUBMED, Disponível em: <https://www.ncbi.nlm.nih.gov/pubmed/> [Acessado em 18/06/2019]."),
  (44, "MEDLINEM, Disponível em: <https://www.nlm.nih.gov/bsd/pmresources.html> [Acessado em 18/06/2019]."),
  (45, "Ros, R; Runeson, P; Bjarnason, E - A Machine Learning Approach for Semi-Automated Search and Selection in Literature Studies, n.Jun, p 118-127, 2017"),
  (46, "M. Miwa, J. Œomas, A. O’Mara-Eves, and S. Ananiadou. 2014. Reducing Systematic Review Workload Œrough Certainty-based Screening. Journal of Biomedical Informatics 51 (2014), 242–253. DOI:hŠp://dx.doi.org/10.1016/j.jbi.2014.06.005"),
  (47, "Tan, A.-H. Text Mining: The state of the art and the challenges. In Proceedings of the pakdd, Workshop On Knowledge Disocovery From Advanced Databases. (1999)."),
  (48, "C. Cortes and V. Vapnik. 1995. Support-Vector Networks. Machine Learning 20, 3 (1995), 273–297. DOI:http://dx.doi.org/10.1007/BF00994018"),
  (49, "Thomas J, McNaught J, Ananiadou S. Applications of text mining within systematic reviews. Res Synth Methods 2011;2(1):1–14."),
  (50, "Wei, X., & Croft, W. B. (2006). Lda-based document models for ad-hoc retrieval. In Proceedings of the 29th annual international acm sigir conference on research and development in information retrieval."),
  (51, "Wallace B, Trikalinos T, Lau J, Brodley C, Schmid C. Semi-automated screening of biomedical citations for systematic reviews. BMC Bioinform 2010;11(1):55."),
  (52, "Lefebvre C, Manheimer E, Glanville J. Cochrane handbook for systematic reviews of interventions, version 5.1.0 edition, chap. 6; 2011."),
  (53, "Sarmento, Luís. “Medidas de Associação”. Simpósio Doutoral Linguateca, 3, 4 Outubro 2006."),
  (54, "Bruce, P,. BRUCE, Andrewv - Estatística Prática para Cientista de Dados: 50 conceitos essenciais. 1ª ed. Editora Alta Books, 2019. ISBN 978-85-508-0603-7"),
  (55, "Hotho, A., A. Nürnberger, et al. (2005). \"A brief survey of text mining.\" LDV Forum GLDV Journal for Computational Linguistics and Language Technology."),
  (56, "Andrade, M. A. ,Helena, P. — Aplicação de Técnicas de Mineração de Textos para Classificação de Documentos: um Estudo da Automatização da Triagem de Denúncias na CGU. Brasília: Universidade de Brasília, 2015, Dissertação de Mestrado em Computação Aplicada."),
  (57, "Weiss, S., N. Indurkhya, Zhang T., and Damerau, F. Text Mining: Predictive Methods for Analyzing Unstructured Information. Springer, 2004"),
  (58, "Santos, C. M. - Classificação de Documentos com Processamento de Linguagem Natural. Coimbra: Instituto Superior de Engenharia de Coimbra, 2015. Dissertação de mestrado em Informática e Sistemas"),
  (59, "A. O’Mara-Eves, , J. Tomas, J. McNaught, M. Miwa, and S. Ananiadou. 2015. Using Text Mining for Study Identification in Systematic Reviews: A Systematic Review of Current Approaches. Systematic Reviews 4, 1 (2015), 5. DOI: http://dx.doi.org/10.1186/2046-4053-45"),
  (60, "Rodrigues, H. J. F. - Ferramenta para Text Mining em Textos completos. Porto: Universidade do Porto, 2016. Dissertação de mestrado em Engenharia Informática e Computação"),
  (61, "Aranha, C. N.; Vellasco, M. Uma abordagem de pré-processamento automático para Mineração de textos em português: sob o enfoque da inteligência computacional. Pontifícia Universidade Católica do Rio de Janeiro, Rio de Janeiro, RJ, 2007"),
  (62, "Indurkhya, N.; Damerau, F. J. Handbook of natural language processing. [S.l.]: CRC Press, 2010."),
  (63, "Gomes, H. J. C. Text mining: análise de sentimentos na classificação de notícias. Instituto Superior de Estatística e Gestão de Informação. Universidade Nova de Lisboa. Portugal. 2012"),
  (64, "Bird, S., Klein, E., Loper, E. - Natural Language Processing with Python. 1ª. Ed. Sebastopol: Editora O’Reilly Media, Inc, 2009. ISBN: 978-0-596-51649-9."),
  (65, "Manning, C. D. et al. Introduction to information retrieval. [S.l.]: Cambridge university press Cambridge, 2008."),
  (66, "Martins,C. A.; Monard,M.; Matsubara, E. T. - Reducing the dimensionality of bag-ofwords text representation used by learning algorithms. In Proceedings of The Third IASTED International Conference on Artificial Intelligence and Applications (AIA 2003), Benalmádena, Espanha. (to be published), volume 38, 2003. 6"),
  (67, "Wives, L. K.; Loh, S. Recuperação de informações usando a expansão semântica e a lógica."),
  (68, "Brito, E. M. N. D. Mineração de textos: detecção automática de sentimentos em comentários nas mídias sociais. Projetos e Dissertações em Sistemas de Informação e Gestão do Conhecimento, v. 6, n. 1, 2017"),
  (69, "Bergmanis, B,; Goldwater, S - Training Data Augmentation for Context-Sensitive Neural Lemmatization Using Inflection Tables and Raw Text, n.Apr 2019."),
  (70, "Martin F. Porter. An Algorithm for Suffix Stripping. Program, 14(3):130–137, 1980. 26"),
  (71, "Oguri, P.; Milidií, R. L.; Renteria, R. Machine Learning for Sentiment Classification. MsC Thesis — Department of Informática, Pontifícia Universidade Católica do Rio de Janeiro. Rio de Janeiro. 2006"),
  (72, "Magalhães, B. N.. “Avaliação de métodos não-supervisionados de seleção de atributos para Mineração de Textos”. Fevereiro 2009."),
  (73, "Santos, B.. “Níveis de processamento de texto”. 2006"),
  (76, "Alexandra I. M. Alves, Modelo de representação de texto mais adequado à Classificação. Porto: Instituto Superior de Engenharia do Porto, 2010. Dissertação para obtenção do Grau de Mestre em Engenharia Informática Área de especialização em Tecnologias do Conhecimento e Decisão."),
  (77, "Martins, C., Monard, M., E. Matsubara. Uma Metodologia para Auxiliar na Seleção de Atributos Relevantes usados por Algoritmos de Aprendizado no Processo de Classificação de Textos, 2007, Universidade de São Paulo."),
  (78, "TF-IDF, \"term frequency-inverse document frequency\". Disponível em: < http://www.tfidf.com > [Acesso em 16/06/2019]."),
  (79, "Prabowo, R.; Thelwall, M. Sentiment analysis: A combined approach. Journal of Informetrics, Elsevier, v. 3, n. 2, p. 143–157, 2009."),
  (80, "Martins, J. Classificação de páginas na internet. Trabalho de Conclusão (Mestrado). Instituto de Ciências Matemáticas e de Computação. USP. São Carlos, 2003."),
  (81, "Tan, A.-H. (1999). Text mining: The state of the art and the challenges. In Proceedings of the pakdd 1999 workshop on knowledge disocovery from advanced databases."),
  (82, "Martins,C. A. – Uma abordagem para pré-processamento de dados textuais em algoritmo de aprendizado. São Carlos: Unviersidade de São Paulo – USP, 2003. Tese de Doutorado em Ciências Matemática e de Computação."),
  (83, "SCIKIT-LEARN, \"1.4 Support Vector Machines\". Disponível em: <http://scikitlearn.org/stable/modules/svm.html> [Acesso em 16/06/2019]."),
  (84, "LI, F.-F.; PERONA, P. A bayesian hierarchical model for learning natural scene categories. In: Proceedings of the 2005 IEEE Computer Society Conference on Computer Vision and Pattern Recognition (CVPR’05) - Volume 2 - Volume 02 . Washington, DC, USA: IEEE Computer Society, 2005. (CVPR ’05), p. 524–531. ISBN 0-7695-2372-2. Disponível em: <http://dx.doi.org/10.1109/CVPR.2005.16>"),
  (85, "Broniatowski, D. A.; Magee, C. L. Analysis of social dynamics on fda panels using social networks extracted from meeting transcripts. In: SocCom. [s.n.], 2010. Disponível em: <http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=5591237&tag=1>"),
  (86, "Liu, B. Sentiment analysis and opinion mining. Synthesis Lectures on Human Language Technologies, Morgan & Claypool Publishers, v. 5, n. 1, p. 1–167, 2012."),
  (87, "Brito Nunes, E. M. - Mineração de Textos: Detecção automática de sentimentos em comentários nas mídias sociais. Belo Horizonte, Universidade Fundação Mineira de Educação e Cultura, 2017. Dissertação de Mestrado em Sistemas de Informação e Gestão do Conhecimento"),
  (88, "Gonçalves, T. et al. Analysing part-of-speech for portuguese text classification. In: Computational Linguistics and Intelligent Text Processing. [S.l.]: Springer, 2006. p. 551–562."),
  (89, "Gibbon, Dafydd; Moore, Roger; Winski, Richard (1998). Handbook of Standards and Resources for Spoken Language Systems: Spoken language characterisation. Berlim: Walter de Gruyter. ISBN 9783110157345. Consultado em 1 de março de 2018"),
  (90, "Bernardo N. B. Lima, Leandro Martins Cioletti, Marcelo de O. Terra Cunha, Gastão A. Braga; Entropia: introdução à Teoria Matemática da (des)Informação; Departamento de Matemática - UFMG."),
  (91, "Röder, M., A. Both, and Hinneburg, A.. Exploring the Space of Topic Coherence Measures. In Proceedings of WSDM, 2015"),
  (92, "N. Aletras and M. Stevenson. Evaluating topic coherence using distributional semantics. In Proc. of the 10th Int. Conf. on Computational Semantics (IWCS'13), pages 13--22, 2013"),
  (93, "Chen, C.; Liaw, A.; Breiman, L. Using random forest to learn imbalanced data. [S.l.],july 2004. Disponível em: xtf.lib.berkeley.edu/reports/SDTRWebData/accessPages/666.html."),
  (94, "Lento, G. C - Random forest em dados desbalanceados: uma aplicação na modelagem de churn em seguro saúde. Rio de Janeiro: Fundação Getúlio Vargas Escola De Matemática Aplicada, 2017. Dissertação para o título de Mestre Em Modelagem Matemática Da Informação."),
  (95, "Piri, S., Delen, D., and Liu, T. (2018). A synthetic informative minority over-sampling (simo) algorithm leveraging support vector machine to enhance learning from imbalanced datasets. Decision Support Systems, 106, 15–29"),
  (96, "Lloret, E., & Palomar, M. Text summarization in progress: A literature review. Artificial Intelligence Review, 37(1), 1-41, 2012."),
  (97, "G. Carenini, R. Ng, and A. Pauls, “Multi-document summarization of evaluative text,” Proceedings of the European Chapter of the Association for Computational Linguistics (EACL), pp. 305–312, 2006."),
  (98, "SUMARIZATION.SUMMARIZER – TEXTRANK SUMMARISER Disponível em: < https://radimrehurek.com/gensim/summarization/summariser.html>[Acessado em 31/11/2019]"),
  (99, "Amaral, Daniela O. F. - O Reconhecimento De Entidades Nomeadas Por Meio De Conditional Random Fields Para A Língua Portuguesa. Pontifícia Universidade Católica Do Rio Grande Do Sul, Faculdade De Informática, 2013. Dissertação apresentada como requisito parcial à obtenção do grau de Mestre em Ciência da Computação. Disponível em:< http://tede2.pucrs.br/tede2/handle/tede/5246>"),
  (100, "Dos Santos, Ângelo F. - Sumarização Automática de Texto. Covilhã: Universidade da Beira Interior, 2012. Dissertação para obtenção do Grau de Mestre em Engenharia Informática."),
  (101, "Ferreira, R., Cabral, L., Lins, R., Silva, G., Freitas, F., Cavalcanti, G., Favaro, L. Assesing sentence scoring techniques for extrative text summarization. Expert Systems with Applications, 5755-5764, 2013. Free Summarizer. Acesso em: 12 de Fevereiro de 2014, Disponível em: http://freesummarizer.com/, 2014"),
  (102, "Barrera, A., & Verma, R. Combining syntax and semantics for automatic extractive single-document summarization. Proceedings of the 13th international conference on computational linguistics and intelligent text processing, 366-377, 2012."),
  (103, "Cormen, Thomas H.; Leiserson, Charles E.; Rivest, Ronald L.; Stein, Clifford (2001), \"Section 22.1: Representations of graphs\", Introduction to Algorithms (Second ed.), MIT Press and McGraw-Hill, pp. 527–531, ISBN 0-262-03293-7."),
  (104, "Rada, M.; Tarau, P - TextRank: Bringing Order into Texts. Department of Computer Science University of North Texas. Detron – TX – U.S.A"),
  (105, "Cruz,F.;Troyano, J.A.;Enríquez,F.; Ortega,F.J-TextRank como motor de aprendizaje en tareas de etiquetado. Disponível em:< https://dialnet.unirioja.es/servlet/articulo?codigo=2675325>"),
  (106, "Mckinney, Wes – Python para Análise de Dados, Tratamento de Dados com Pandas, Numpy e Ipython, 1ª ed. Editora Novatec, 2018, ISBN 978-85-7522-647-6"),
  (107, "Y. Chen, Daniel – Análise de Dados com Python e Pandas 1ª ed. Editora Novatec, ISBN 2018, 978-85-7522-699-5"),
  (108, "Rehurek, R.; Sojka, P. Software Framework for Topic Modelling with Large Corpora. In: Proceedings of the LREC 2010 Workshop on New Challenges for NLP Frameworks,Valletta, Malta. Anais... ELRA, 2010. p.45–50. http://is.muni.cz/publication/ 884893/en."),
  (109, "GENSIM. MODELS. LDA MULTICORE, Disponível em: https://3981349775gh.circleartifacts.com/0/documentation/html/generated/gensim.models.lda multicore.LdaMulticore.html[Acessado em 30/11/2019]"),
  (110, "Ebeid, I.A.; Arango, J.M - Mallet vs GenSim: Topic Modeling Evaluation Report. Mallet vs GenSim: Topic modeling for 20 news groups report. n.April 23, 2016"),
  (111, "Machine Learning for Language Toolkit, Disponível em:< http://mallet.cs.umass.edu/ > [Acessado em 31/11/2019]"),
  (112, "Li, W., & McCallum, A. (2006). Pachinko allocation: DAG-structured mixture models of topic correlations. In Proceedings of the 23rd international conference on Machine learning (pp. 577-584). ACM"),
  (113, "Blei, D., Griffiths, T., Jordan, M., Tenenbaum, J. Hierarchical topic models and the nested Chinese restaurant process. In Advances in Neural Information Processing Systems 16, Cambridge, MA, MIT Press, 2004."),
  (114, "readthedocs.org, Disponivel em: https:// readthedocs.org/projects/pyldavis/downloads/pdf/latest/> [Acessado em 02/12/2019]"),
  (115, "Borras S. and Di Ciaccio A.. Measuring the prediction error a comparison of crossvalidation, bootstrap and covariance penalty methods. Computational Statistics and Data Analysis, Borra e Ciaccio(2010), 54:2976-2989."),
  (116, "SCIKIT-LEARN-DOCS,<https://scikit-learn.org/stable/_downloads/scikit-learndocs.pdf> [Acesso em 20/06/2019]."),
  (117, "SCIKIT-LEARN, \"C-Support Vector Classification.\" Disponível em: <https://scikitlearn.org/stable/_downloads/scikit-learn-docs.pdf>[Acesso em 20/06/2019]."),
  (118, "Kohavi(1995) Ron Kohavi. Measuring the prediction error. a comparison of c. Computacional Statistics and Data Analysis, 1:2976-2989."),
  (119, "H. Wu and R. Luk and K. Wong and K. Kwok. \"Interpreting TF-IDF term weights as making relevance decisions\". ACM Transactions on Information Systems, 26 (3). 2008."),
  (120, "Gartlehner, G., Wagner, G., Lux, L. et al. Assessing the accuracy of machine-assisted abstract screening with DistillerAI: a user study. Syst Rev 8, 277 (2019). https://doi.org/10.1186/s13643-019-1221-3"),
  (122, "Jurasfsky D, Martin J H., Speech and Language Processing. An Introduction to Natural Language Processing, Computational Linguistics, and Speech Recognition, Third Edition draft, 2018."),
  (123, "Lorena, A, C; De Carvalho, A,C,P,L,F - Uma Introdução às Support Vector Machines. Departamento de Ciência da Computação, Instituto de Ciências Matemáticas e de Computação, Universidade de São Paulo, Centro de Matemática, Computação e Cognição, Universidade Federal do ABC."),
  (124, "Boser, B. E.; Guyon, I. M.; Vapnik, V. N. A Training Algorithm for Optimal Margin Classifiers. In: ANNUAL WORKSHOP ON COMPUTACIONAL LEARNING, 5, 1992, Pittsburgh. ACM Press. Pittsburgh: Haussler D, jul 1992. p.144-152 ."),
  (125, "Drucker, H.; Burges, C. J.; Kaufman, L.; Smola, A.; Vapnik, V. Support vector regression machines. Advances in neural information processing systems, Morgan Kaufmann Publishers, p. 155–161, 1997."),
  (126, "Saradhi, V., Kamik, H., Mitra, P. A Decomposition Method for Support Vector Clustering. In Proc. of the 2nd International Conference on Intelligent Sensing and Information Processing (ICISIP), p. 268-271, 2005."),
  (127, "C. Campbell. An introduction to kernel methods. In R. J. Howlett and L. C. Jain, editors, Radial Basis Function Networks: Design and Applications, pages 155–192, Berlin, 2000. Springer Verlag."),
  (128, "C.-C. Chang and C.-J. Lin. LIBSVM: a library for support vector machines. Disponível em: <http://www.csie.ntu.edu.tw/~cjlin/libsvm/>. Acessado em: 02/07/2020."),
  (129, "De Paula Faleiros, T; De Andrade Lopes, L: Modelos Probabilísticos De Tópicos: Desvendando o Latent Dirichlet Allocation, Relatórios Técnicos, Universidade De São Paulo, Instituto de Ciências Matemáticas e de Computação, São Carlos – SP, 2016"),
  (130, "Lanckriet, G. R. G.; Cristianini, N.; Bartlett, P.; Ghaoui, L. E.; Jordan, M. I. (2004). \"Learning the kernel matrix with semidefinite programming\". Journal of Machine Learning Research. 5: 27–72 [p. 29]"),
  (131, "Gunn, S.. Support vector machines for classification and regression. Technical report, Image Speech & Intelligent Systems Group, University of Southampton, 1998."),
  (132, "Lorena, Ana Carolina; Carvalho, André C. P. L. F. de. Uma Introdução às Support Vector Machines. Revista de Informática Teórica e Aplicada (RITA) V.14, n.2, p.43-67, 2007."),
  (133, "Faceli, K.. et al. Inteligência Artificial: uma abordagem de aprendizagem de máquina."),
  (134, "Rio de Janeiro: LTC, 2011. ASANO, A. Support vector machine and kernel method. Pattern information processing (2004 Autumn Semester), Session 12, 2005."),
  (135, "Chamasemani, F. F.; Singh, Y. P.. Multi-class Support VectorMachine (SVM) classifiersAn Application in Hypothyroid detection and Classification. In: Sixth International Conference on Bio-Inspired Computing: Theories and Applications, 2011."),
  (136, "Souto, Marcilio Carlos Pereira de. et al. Técnicas de Aprendizado de Máquina para problemas de Biologia Molecular, p 103–152. In: Minicursos de Inteligência Artificial, Jornada de Atualização Científica em Inteligência Artificial, XXIII Congresso da Sociedade Brasileira de Computação, 2003."),
  (137, "El-Naqa, I. et al. A support vector machine approach for detection of microcalcifications. IEEE Transactions on Medical Imaging, 2(12): 1562 - 1563, December 2002."),
  (138, "Albuquerque, Rafael W. de. Monitoramento da cobertura do solo no entorno de hidrelétricas utilizando o classificador SVM (Support Vector Machines). 2012. 95 p. Dissertação (Mestrado em Engenharia de Transportes) – Escola Politécnica da Universidade de São Paulo. Departamento de Engenharia de Transportes. São Paulo, 2012."),
  (139, "Faceli, K.. et al. Inteligência Artificial: uma abordagem de aprendizagem de máquina. Rio de Janeiro: LTC, 2011"),
  (140, "Araújo, Keven M.. Et al. Utilização do Algoritmo de Máquina de vetores de suporte (SVM) para predição de dados climáticos. Trabalho de Conclusão de Curso (Bacharel em Ciência da Computação) – Universidade Luterana de Palmas, 2015"),
)

#for (n, t) in refs {
  block(below: 0.55em, par(hanging-indent: 0.9cm, [[#n] #t]))
}
